# Configuration module
from .settings import (
    LLM_CONFIG,
    DEFAULT_WEIGHTS,
    DEFAULT_THRESHOLDS,
    GRADE_MAPPING,
    DEFAULT_HARD_FILTERS,
    SIGNAL_LIBRARY,
    INDUSTRY_CATEGORIES,
    TECH_CATEGORIES,
)
